"""User avatar

Revision ID: 007523ca38d7
Revises: 11d66f33fa43
Create Date: 2023-08-21 14:52:27.185228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007523ca38d7'
down_revision = '11d66f33fa43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
